apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-frontend
  name: udagram-api-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-frontend
  template:
    metadata:
      labels:
        service: udagram-api-frontend
        api: external
    spec:
      containers:
      - image: ductu1305/udagram-api-frontend:v1
        name: udagram-api-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
