apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = ASIASDSGHVWQS3V7NOLK
    aws_secret_access_key = ueQx3wM90WLHpFMbpBh85Nc8SmdKRdMEnJ06bCGO
    aws_session_token = IQoJb3JpZ2luX2VjEOX//////////wEaCXVzLXdlc3QtMiJIMEYCIQDL3puuynA3FqMc+of2EJrN6SAornWKgzAU5Po2/HX5lQIhALTsqLtgLXRDVy6YbRPInmZKgfOX2jnXFBCdeAMzvUU4Kr4CCD4QARoMMTQ1MTAyNDUwMDgxIgymDSMrzjC69OLNlK4qmwJgWbQRBX/kMKO8/RY6snYQXZirmbsg2P/VaLyC7MUAZH9foJK+qRFjvuuPbzDeNzVFNFn8Iaxqzv21IdMIZiYaNeAwzvkO6kmggExHkUDy+5S7yPkRN5VERy/RtUNJv3K9BSoR4kIl3TP65JMoXwo0VJzEbZyuA5TtVI664DoIF/N6n+TNLYZXJAJBZ6GCYvTbzIQYZpoVijKtsvGCBhbA0gLy90+vkyV1gNBg4mk8wZcfRho/rBBJqj5dULAwUoujqBHtEZ41717h1g+/ImMcO3jAuxO4um9J4HLCEECL6eTqRNcV/vbSNgSYRTd4vsIW7Ur5dTIeyvH0yHErplhaaUFLPtSl4NLMZsWcJa4NVTLcGnIluq67DFgSMPznkrgGOpwBcjSr8BcEdAMqgA/S27iwndM8Bfv4SCItBO69cdkCnRH9vPXDmkW4GVv9iyd7FUuAZsQy+2+uSRGDnT/d0zGKixlXtJrtDd/dPiglXQX6RJxZHpJpYH4e+buJuiG5czj4J1NFoNe/zB+QJGlDripBZ+OKFThpW3r6elgnN22NxHya1oa0K+yOI5RQgu4Focm1aUCTNGa82rsVWBpO