apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: udagram-frontend
  template:
    metadata:
      labels:
        run: udagram-frontend
        api: external
    spec:
      containers:
        - image: ductu1305/udagram-frontend
          name: udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always